# Generated by Django 4.2.8 on 2024-08-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="HtmlContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        default="default_image.jpg",
                        null=True,
                        upload_to="uploads/product/",
                    ),
                ),
                (
                    "post_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
