# Generated by Django 4.2.8 on 2024-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_htmlcontent"),
    ]

    operations = [
        migrations.RemoveField(model_name="htmlcontent", name="image1",),
        migrations.RemoveField(model_name="htmlcontent", name="post_date",),
        migrations.AddField(
            model_name="htmlcontent",
            name="category",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
