# Generated by Django 4.2.8 on 2024-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_htmlcontent_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlcontent",
            name="image1",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="uploads/product/"
            ),
        ),
    ]
