# Generated by Django 4.2.8 on 2024-08-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_htmlcontent_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlcontent",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="store.category",
            ),
        ),
    ]
