# Generated by Django 4.2.8 on 2024-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="items",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
